zeit/awesome-zeit

- README.md
The tool I use for my projects from CI
> Added link to now-pipeline

- README.md
Added two deployment link and their src.
> Deployments section.

- README.md
> Declarative routing for React.

- README.md
Nice list!
This PR adds [micro-compress](https://github.com/joakimbeng/micro-compress) as suggested in [this comment](https://github.com/zeit/micro-list/issues/11#issuecomment-248866428)
> Added micro-compress in new Libraries section

- README.md
@leo couldn't create an automatic revert so here's a counter PR.
> Remove React Router

- README.md
As per [this request](https://twitter.com/zeithq/status/794582118940676097) on twitter, adding this trivial example to this repository.
> added now-service-example

- README.md
> Added index

- README.md
Added example for using graphql
> Micro graphql

- README.md
micro-link is a minimalistic microservice to generate and resolve sharable dynamic link (a.k.a deeplink)
> Added micro-link under Deployment Examples

- README.md
> Add micro-route & micro-stats

- README.md
> Add micro-method-router

- README.md
Adds a link to [https://github.com/jesseditson/fs-router](https://github.com/jesseditson/fs-router)
> Add fs-router

- README.md
Including [create-micro](https://github.com/romuloalves/create-micro) in `Boilerplates`.
> Including create-micro

- README.md
https://github.com/mazlix/meteor-now tool to deploy meteorJS apps using now.
> Add meteor-now

- README.md
> Revert "Add next-new"

- README.md
- [fe-lenses.now.sh](https://fe-lenses.now.sh/) - A really micro micro-service for advanced math
- [go.now.sh](https://go.now.sh) - A personal tinyurl service
> Add fe-lenses.now.sh & go.now.sh to Now Showcase.

- README.md
Oops, a stupid mistake, copy & paste & forgot to update description >.<
> Fix description of fe-lenses.now.sh

- README.md
I'd like to add 3 of my microservices to the list of Now Showcases, I think they're all pretty good examples of very small microservices.
If there's anything that needs changing, or if you have any feedback, let me know ✌️
> Add up.now.sh, e.now.sh, f.now.sh to Now Showcase

- README.md
not sure if thats the right place or if you even want this in here?
> add now-dashboard

- README.md
- now4j is a Java client
- know is a Kotlin client
> Add now4j and know API clients

- readme.md
https://shot.now.sh
https://mess.now.sh
https://md.now.sh
> Add shot.now.sh, mess.now.sh, md.now.sh

- readme.md
This is a proxy server used to run alias path in your local environment for development.
> Add now-server

- readme.md
This links to a cool experiment which uses `docker` deployments on now.sh to recreate a basic hello world from the Kitura framework. 
> Cool to illustrate different stacks than the ones we are used to see on now.sh and the power behind `docker` deployments.  😄
> Add server-side swift example

- readme.md
> add next.js-typescript-starter-kit

- readme.md
thanks! feel free to edit description or move to another section
> add project to showcase

- readme.md
Hi, i've added the links for ZEIT's spectrum communities.
> add spectrum links

- readme.md
Hi, I saw that this cool service was missing, hope you'll merge it! :)
> add mobile.now.sh

- readme.md
Hi, I misspelled ZEIT in my previous PR as "Zeit", correcting that in this PR. Thanks!
> capitalize ZEIT

- readme.md
Hi, though it'd be cool to add this microservice. Thanks :)
> add icon.now.sh
